# Tensr Manipulation

In [3]:
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

# Simple Array

In [5]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim)
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


# 2D Array

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12]])
pp.pprint(t)
print(t.ndim)
print(t.shape)

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


# Shape, Rank, Axis

In [8]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [9]:
t = tf.constant([[1,2], [3,4]])
tf.shape(t).eval()

array([2, 2])

In [10]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

# Matmul VS multiply

In [13]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.], [2.]])
tf.matmul(matrix1, matrix2).eval()

array([[ 12.]], dtype=float32)

In [14]:
(matrix1 * matrix2).eval()

array([[ 6.,  6.],
       [ 6.,  6.]], dtype=float32)

# Watch out broadcasting

In [15]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.], [2.]])
(matrix1 + matrix2).eval()


array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

In [16]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1 + matrix2).eval()

array([[ 5.,  5.]], dtype=float32)

# Random values for variable initializations 

In [18]:
tf.random_normal([3]).eval()

array([-1.09976327,  1.33929861, -0.65822083], dtype=float32)

In [20]:
tf.random_uniform([2]).eval()

array([ 0.29168022,  0.65593851], dtype=float32)

In [22]:
tf.random_uniform([2, 3]).eval()

array([[ 0.37876809,  0.55474412,  0.15736187],
       [ 0.08831561,  0.82258964,  0.23499298]], dtype=float32)

# Reduce Mean/Sum

In [23]:
tf.reduce_mean([1, 2], axis=0).eval()

1

In [25]:
x = [[1., 2.], [3., 4.]]
tf.reduce_mean(x).eval()

2.5

In [26]:
tf.reduce_mean(x, axis = 0).eval()

array([ 2.,  3.], dtype=float32)

In [27]:
tf.reduce_mean(x, axis = 1).eval()

array([ 1.5,  3.5], dtype=float32)

In [29]:
tf.reduce_mean(x, axis = -1).eval()

array([ 1.5,  3.5], dtype=float32)

In [28]:
tf.reduce_sum(x).eval()

10.0

In [30]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [31]:
tf.reduce_sum(x, axis=1).eval()

array([ 3.,  7.], dtype=float32)

In [32]:
tf.reduce_mean(tf.reduce_sum(x, axis = -1)).eval()

5.0

# Argmax with axis 

In [33]:
x = [[0, 1, 2], [2, 1, 0]]
tf.argmax(x, axis = 0).eval()

array([1, 0, 0], dtype=int64)

In [34]:
tf.argmax(x, axis = 1).eval()

array([2, 0], dtype=int64)

In [36]:
tf.argmax(x, axis = -1).eval()

array([2, 0], dtype=int64)

# Reshape, squeeze, expand_dims

In [37]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
t.shape

(2, 2, 3)

In [38]:
tf.reshape(t, shape = [-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
tf.reshape(t, shape = [ -1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [40]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2])

In [41]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]])

# One hot 

In [42]:
tf.one_hot([[0], [1], [2], [0]], depth = 3).eval()

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [43]:
t = tf.one_hot([[0], [1], [2], [0]], depth = 3)
tf.reshape(t, shape = [-1, 3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

# Casting 

In [44]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [45]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

# Stack 

In [46]:
x = [1,4]
y = [2, 5]
z = [3, 6]

tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
tf.stack([x, y, z], axis = 1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

# Ones like and Zeros like

In [48]:
x  = [[0, 1, 2], [2, 1, 0]]
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [49]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

#  Zip

In [51]:
for x, y, in zip([1, 2, 3], [4, 5, 6]):
    print (x, y)

1 4
2 5
3 6


In [54]:
for x, y, z, in zip ([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print (x, y, z)

1 4 7
2 5 8
3 6 9


# Transpose 

In [55]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)
    

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [58]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [61]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [62]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
